-- 5. 회원 아이디가 ‘java’인 회원이 예매한 영화의 예매번호, 상영관번호, 좌석번호를 조회하는 SQL문을 작성하시오.

CREATE TABLE MOVIE_MEMBER(
	MEMBER_ID VARCHAR(50) PRIMARY KEY
	, MEMBER_PW VARCHAR(50) NOT NULL
	, MEMBER_NAME VARCHAR(50) NOT NULL
	, MEMBER_TEL VARCHAR(50) NOT NULL
);

CREATE TABLE THEATER(
THEATER_NUM INT PRIMARY KEY AUTO_INCREMENT
, THEATER_NAME VARCHAR(50) NOT NULL
, SEAT_NUM VARCHAR(50) NOT NULL
, MEMBER_ID VARCHAR(50) REFERENCES MOVIE_MEMBER (MEMBER_ID)
);

CREATE TABLE SEAT(
SEAT_CODE INT PRIMARY KEY AUTO_INCREMENT
, COL_NUM INT NOT NULL 
, ROW_NUM VARCHAR(10) NOT NULL
, IS_SEAT VARCHAR(10) NOT NULL
,THEATER_NUM INT REFERENCES THEATER (THEATER_NUM)
);

CREATE TABLE TICKET(
TICKET_NUM INT PRIMARY KEY AUTO_INCREMENT
, MEMBER_ID VARCHAR(50) REFERENCES MOVIE_MEMBER(MEMBER_ID)
, THEATER_NUM INT REFERENCES THEATER (THEATER_NUM)
, SEAT_CODE INT REFERENCES SEAT(SEAT_CODE)
);

SELECT 
	TICKET_NUM
	,THEATER_NUM
	,SEAT_CODE
FROM TICKET
INNER JOIN movie_member
ON ticket.MEMBER_ID = movie_member.MEMBER_ID
WHERE ticket.MEMBER_ID = 'java';







-- 6. 한 회원이 인기 영화인 ’듄‘을 예매하기 위해 예매가능여부를 조회한다고 가정하자. 
-- 이 회원은 상영관명이 ’VIP‘인 상영관에서의 영화감상을 원하고 있다. 만약 영화감상이 가능하다면 조회결과로 ’예매가능‘이라는 결과가 나와야하고,
 -- 불가능하다면 ’예매할 수 있는 좌석이 없습니다.‘라는 문구가 조회되어야 한다. 위와 같이 실행되는 SQL문 작성하시오.

SELECT 
	(SELECT THEATER_NAME FROM theater WHERE THEATER_NAME = 'VIP') AS 'VIP',
	CASE
		WHEN IS_SEAT = 'Y' THEN '예매가능'
		ELSE '예매할 수 있는 좌석이 없습니다.' 
	END AS '좌석배정유무'
FROM ticket
INNER JOIN seat
ON ticket.SEAT_CODE = seat.SEAT_CODE
INNER JOIN theater
ON ticket.THEATER_NUM = theater.THEATER_NUM
INNER JOIN movie_member
ON ticket.MEMBER_ID = movie_member.MEMBER_ID
WHERE ticket.MEMBER_ID = 'java';






